  # .github/dependabot.yml
    version: 2
    updates:
  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # APT (for Linux builds)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
  # Node.js (if we use npm for frontend or tooling)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  # Python (for scripts, virtualenv, packaging)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  # Debian packaging (debian/control, debian/changelog, etc.)
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
